### ISSUE TITLE
Not work on Andriod Studio. Got connection internet errors

### ISSUE THREAD

**Issue by clipvui2512** [maoxiao/fb_ssl_pinning#1]
Hi
What is your android emulator software?

**Comment by maoxiao** [comment]
> Hi
> What is your android emulator software?

I tested  it on [nox](https://en.bignox.com/).  Please make sure the emulator is rooted.

**Comment by whoant** [comment]
![image](https://user-images.githubusercontent.com/17638137/54472430-fa679800-47fa-11e9-9de7-4af558c47c4a.png)
it's error, Can you fix it ??

**Comment by maoxiao** [comment]
> ![image](https://user-images.githubusercontent.com/17638137/54472430-fa679800-47fa-11e9-9de7-4af558c47c4a.png)
> it's error, Can you fix it ??

Perhaps you are not running burpsuite via latest JDK because you are having **"no cipher suites in common"** error. Please update your [JDK](https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html), then try again.

**Comment by whoant** [comment]
> > ![image](https://user-images.githubusercontent.com/17638137/54472430-fa679800-47fa-11e9-9de7-4af558c47c4a.png)
> > it's error, Can you fix it ??
> 
> Perhaps you are not running burpsuite via latest JDK because you are having **"no cipher suites in common"** error. Please update your [JDK](https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html), then try again.
![image](https://user-images.githubusercontent.com/17638137/54473066-854d9000-4805-11e9-90cc-0511b0ba5d80.png)
I updated JDK, but it still fails, can you fix it ??
