### ISSUE TITLE
I tested in NOX simulator, but can not worked

### ISSUE THREAD

**Issue by esingtse** [maoxiao/fb_ssl_pinning#2]
I follow your steps, but the packet grab in Charles is still posed against SSL. Is it necessary to rely on the xposed framework and "just trust me"?

**Comment by esingtse** [comment]
BTW, my facebook versions is 210.0.0.43.119 （x86, Android 8.0+, 280-640dpi ）

**Comment by maoxiao** [comment]
As I mentioned in the readme, please use Burp Suite instead. Charles does not work in this case.

**Comment by esingtse** [comment]
![image](https://user-images.githubusercontent.com/24379369/55388072-302faf00-5565-11e9-85c0-3c1de24b428f.png)
I updated my JDK version to 11. And successfully retrieved the response from Facebook. However, I can not get the params from the request, because it is displayed in garbled code. Do you have any Suggestions?

**Comment by esingtse** [comment]
Burp Suite throws an exception in Alerts that is: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated

**Comment by maoxiao** [comment]
In Burp Suite, Proxy => Options :  enable "**Unpack gzip / deflate in requests**". Then you will be able to see the params in the request.

**Comment by esingtse** [comment]
Well, thanks a lot for your help.
